ALTER TABLE public.clients 
  ADD COLUMN IF NOT EXISTS address_cep text,
  ADD COLUMN IF NOT EXISTS address_street text,
  ADD COLUMN IF NOT EXISTS address_number text,
  ADD COLUMN IF NOT EXISTS address_complement text,
  ADD COLUMN IF NOT EXISTS address_neighborhood text,
  ADD COLUMN IF NOT EXISTS address_state text,
  ADD COLUMN IF NOT EXISTS housing_type text,
  ADD COLUMN IF NOT EXISTS residence_time text,
  ADD COLUMN IF NOT EXISTS reference_name_2 text,
  ADD COLUMN IF NOT EXISTS reference_phone_2 text,
  ADD COLUMN IF NOT EXISTS reference_relation text,
  ADD COLUMN IF NOT EXISTS reference_relation_2 text,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS education_level text,
  ADD COLUMN IF NOT EXISTS dependents integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mother_name text,
  ADD COLUMN IF NOT EXISTS father_name text,
  ADD COLUMN IF NOT EXISTS rg text,
  ADD COLUMN IF NOT EXISTS rg_issuer text,
  ADD COLUMN IF NOT EXISTS cnh_number text,
  ADD COLUMN IF NOT EXISTS cnh_category text,
  ADD COLUMN IF NOT EXISTS employer_cnpj text,
  ADD COLUMN IF NOT EXISTS employer_cep text,
  ADD COLUMN IF NOT EXISTS employer_address text,
  ADD COLUMN IF NOT EXISTS employer_phone text,
  ADD COLUMN IF NOT EXISTS gross_income numeric,
  ADD COLUMN IF NOT EXISTS profession text;