// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baxpayrwcfdoapnihwhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJheHBheXJ3Y2Zkb2Fwbmlod2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNTkxODcsImV4cCI6MjA5MDczNTE4N30.7KopOVyGviDdRIFb6R-xkp5kHcIPvzukoPcrY2wY_f8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});